[project]
name = 'Cosmic-String-Detection-and-Manipulation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cosmic-string-nft]
path = 'contracts/cosmic-string-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.manipulation-technique-marketplace]
path = 'contracts/manipulation-technique-marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.observation-coordination]
path = 'contracts/observation-coordination.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
